"""empty message

Revision ID: d585a84345e2
Revises: 
Create Date: 2023-12-07 09:56:28.673422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd585a84345e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('prompt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_question', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('prompt_id', name=op.f('pk_prompts'))
    )
    op.create_table('responses',
    sa.Column('response_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response_answer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('response_id', name=op.f('pk_responses'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('responses')
    op.drop_table('prompts')
    # ### end Alembic commands ###
