"""empty message

Revision ID: ec361353695b
Revises: d585a84345e2
Create Date: 2023-12-07 12:54:41.723369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec361353695b'
down_revision = 'd585a84345e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.alter_column('prompt_question',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.alter_column('response_answer',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.alter_column('response_answer',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.alter_column('prompt_question',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
